### ISSUE TITLE
[BUG] globalCanDestroy and globalCanPlaceOn don't work

### ISSUE THREAD

**Issue by pe3ep** [SuperNeon4ik/NoxesiumUtils#4]
Error in the console:
```
08.06 21:26:18 [Server] [INFO] java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.NoxesiumUtils.lambda$registerCommands$7(NoxesiumUtils.java:111)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:117)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:104)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:79)
08.06 21:26:18 [Server] [INFO] at NoxesiumUtils-1.4.jar//me.superneon4ik.noxesiumutils.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:252)
08.06 21:26:18 [Server] [INFO] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
08.06 21:26:18 [Server] [INFO] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
08.06 21:26:18 [Server] [INFO] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2289)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
08.06 21:26:18 [Server] [INFO] at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
08.06 21:26:18 [Server] [INFO] at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18)
08.06 21:26:18 [Server] [INFO] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
08.06 21:26:18 [Server] [INFO] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1343)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
08.06 21:26:18 [Server] [INFO] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1320)
08.06 21:26:18 [Server] [INFO] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1313)
08.06 21:26:20 [Server] [INFO] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
08.06 21:26:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1291)
08.06 21:26:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
08.06 21:26:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
08.06 21:26:20 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:831)
```

Using Pufferfish 1.19.3 as server jar

**Comment by pe3ep** [comment]
globalCanDestroy now works with 1.4.1, but globalCanPlaceOn still has the same error

**Comment by SuperNeon4ik** [comment]
Oops, I see. Sleepy me didn't paste the code in the correct place.

**Comment by SuperNeon4ik** [comment]
Should be fine now. If it's not I'm gonna cry.
